name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build application
        run: ./mvnw package

  docker:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: docker login ghcr.io -u FPeterL -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build . -t ghcr.io/FPeterL/cubix/1/homework/app:springboot
          docker push ghcr.io/FPeterL/cubix/1/homework/app:springboot

  verify:
    name: Verify Docker Image
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Verify Docker Image
        run: ./verify-image.sh
